version: 2.1

jobs:
  hello: 
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo "Hello ğŸ‘‹ğŸ¼, $CIRCLE_USERNAME!"

workflows:
  version: 2.1
  welcome:
    jobs:
      - hello
